# Generated by Django 5.1.6 on 2025-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='00000', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='transit_number',
            field=models.CharField(default='-0000000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
