# Generated by Django 5.1.6 on 2025-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_alter_account_institution_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('branch', 'Branch Transaction'), ('atm', 'Automated Banking Machine'), ('telephone', 'Telephone Banking Personal')], max_length=20, null=True),
        ),
    ]
