# Generated by Django 5.1.6 on 2025-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_alter_transaction_amount_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
