# Generated by Django 5.1.6 on 2025-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0006_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='Budget', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'name', 'type')},
        ),
    ]
