# Generated by Django 5.1.6 on 2025-05-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0007_budget_name_budget_type_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='type',
        ),
    ]
